[project]
name = "Artificial-Neural-Network"
version = "0.1.0"
description = "Default template for PDM package"
dependencies = ["requests>=2.32.4", "numpy>=2.3.1", "matplotlib>=3.10.3"]
requires-python = "==3.12.*"
readme = "README.md"


[tool.pdm]
distribution = false
